Repository Kernel180-BE12/Final-4team-icebang, pull requests merged in 2025-09, with the labels that each got.

#29 기본적 auth 구조 설정
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/controller/AuthController.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/controller/Oauth2CallbackController.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/dto/AuthRequestWrapper.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/dto/DefaultRequestWrapper.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/dto/LoginDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/dto/OAuth2RequestWrapper.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/dto/Oauth2CallbackContent.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/dto/SignUpDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/provider/AuthProvider.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/provider/AuthProviderFactory.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/provider/DefaultProvider.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/provider/OAuth2AuthProvider.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/service/AuthService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/service/AuthServiceImpl.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/service/state/AuthStateService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/service/state/JwtTokenStateService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/auth/service/state/SessionStateService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/config/security/SecurityConfig.java
  apps/user-service/src/main/java/com/gltkorea/icebang/config/security/endpoints/SecurityEndpoints.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/controller/AuthController.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/dto/AuthCredential.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/dto/LoginRequest.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/enums/Role.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/service/AuthService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/service/AuthUserDetailService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/UserStatus.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/model/Users.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/service/SecurityAuthenticateAdapter.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/service/UserAuthService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/entity/Users.java
Labels: enhancement

#39 조직 별 position, role, department return api
  apps/user-service/src/main/java/com/gltkorea/icebang/common/dto/ApiResponse.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/department/dto/DepartmentsCardDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/organization/controller/OrganizationController.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/organization/dto/OrganizationOptionsDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/organization/service/OrganizationService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/position/dto/PositionCardDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/roles/dto/RolesCardDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/dto/UserDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/mapper/OrganizationMapper.java
  apps/user-service/src/main/resources/mybatis/mapper/OrganizationMapper.xml
Labels: enhancement

#45 Email 중복 확인 api
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/controller/UserController.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/dto/CheckEmailRequest.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/dto/CheckEmailResponse.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/service/UserService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/mapper/UserMapper.java
Labels: enhancement

#52 User 가입 api
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/controller/AuthController.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/dto/RegisterDto.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/service/AuthService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/service/UserService.java
  apps/user-service/src/main/java/com/gltkorea/icebang/mapper/AuthMapper.java
  apps/user-service/src/main/resources/mybatis/mapper/AuthMapper.xml
Labels: enhancement

#88 fix: typeHandler가 등록되지 않는 버그
  apps/user-service/src/main/resources/application.yml
Labels: bug

#96 로그아웃 api
  apps/user-service/src/main/java/site/icebang/domain/auth/controller/AuthController.java
  apps/user-service/src/main/resources/sql/01-schema-h2.sql
  apps/user-service/src/test/java/site/icebang/e2e/scenario/UserLogoutFlowE2eTest.java
  apps/user-service/src/test/java/site/icebang/integration/tests/auth/AuthApiIntegrationTest.java
Labels: enhancement

#103 feat: 워크플로우 정의 리스트 api
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/WorkflowCardDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/mapper/WorkflowMapper.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/service/WorkflowService.java
  apps/user-service/src/main/java/site/icebang/global/config/security/SecurityConfig.java
  apps/user-service/src/main/java/site/icebang/global/config/security/endpoints/SecurityEndpoints.java
  apps/user-service/src/main/resources/mybatis/mapper/WorkflowMapper.xml
Labels: enhancement

#161 비동기 호출 시 spanId, traceId가 전파되지 않는 버그 픽스
  apps/user-service/build.gradle
  apps/user-service/src/main/java/site/icebang/domain/workflow/controller/WorkflowController.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/service/WorkflowExecutionService.java
  apps/user-service/src/main/java/site/icebang/global/config/asnyc/AsyncConfig.java
Labels: bug

#169 Workflow history 상세 api
  apps/user-service/src/main/java/site/icebang/domain/workflow/controller/WorkflowHistoryController.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/ExecutionLogDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/JobRunDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/TaskRunDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/WorkflowRunDetailResponse.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/WorkflowRunDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/WorkflowRunLogsResponse.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/mapper/WorkflowHistoryMapper.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/service/WorkflowHistoryService.java
  apps/user-service/src/main/resources/mybatis/mapper/WorkflowHistoryMapper.xml
  apps/user-service/src/main/resources/sql/04-insert-workflow-history.sql
  apps/user-service/src/test/java/site/icebang/integration/tests/workflow/WorkflowHistoryApiIntegrationTest.java
Labels: enhancement

#200 feat: check-session, permissons api에 대한 테스트 코드 작성
  apps/user-service/src/test/java/site/icebang/integration/tests/auth/AuthApiIntegrationTest.java
Labels: documentation

#212 Jackson Timezone 직렬화가 되지 않던 문제 해결
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/ExecutionLogDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/JobRunDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/TaskRunDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/WorkflowRunDto.java
  apps/user-service/src/main/java/site/icebang/global/config/WebConfig.java
  apps/user-service/src/main/resources/application.yml
  apps/user-service/src/main/resources/sql/schema/03-schema-h2-timezone.sql
  apps/user-service/src/test/java/site/icebang/e2e/setup/config/E2eTestConfiguration.java
  apps/user-service/src/test/java/site/icebang/e2e/setup/support/E2eTestSupport.java
  apps/user-service/src/test/java/site/icebang/integration/setup/config/RestDocsConfiguration.java
  apps/user-service/src/test/java/site/icebang/integration/tests/workflow/WorkflowHistoryApiIntegrationTest.java
Labels: bug

#215 ExecutionLog API 구현 및 traceId 일관성 개선
  apps/user-service/src/main/java/site/icebang/domain/log/mapper/ExecutionLogMapper.java
  apps/user-service/src/main/java/site/icebang/domain/log/service/ExecutionLogService.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/controller/WorkflowHistoryController.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/ExecutionLogDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/log/ExecutionLogSimpleDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/log/ExecutionType.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/log/TaskExecutionMessagesDto.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/dto/log/WorkflowLogQueryCriteria.java
  apps/user-service/src/main/java/site/icebang/domain/workflow/model/WorkflowRun.java
  apps/user-service/src/main/resources/mybatis/mapper/ExecutionLogMapper.xml
  apps/user-service/src/main/resources/sql/data/06-insert-execution-log-h2.sql
  apps/user-service/src/test/java/site/icebang/integration/tests/workflow/ExecutionLogApiIntegrationTest.java
Labels: bug, enhancement

#217 User 관련 api test 및 api document 작성
  apps/user-service/src/main/java/site/icebang/domain/user/dto/CheckEmailRequest.java
  apps/user-service/src/main/java/site/icebang/domain/user/mapper/UserMapper.java
  apps/user-service/src/test/java/site/icebang/integration/tests/user/UserApiIntegrationTest.java
Labels: documentation

#218 Gradle 캐싱을 통해 CI (Java) 속도 개선
  .github/workflows/ci-java.yml
  apps/user-service/gradle.properties
  apps/user-service/src/test/java/site/icebang/TestUserServiceApplication.java
  apps/user-service/src/test/java/site/icebang/TestcontainersConfiguration.java
Labels: tech-debt

#221 OCR 처리된 텍스트 RAG prompt context에 추가
  apps/pre-processing-service/app/model/schemas.py
  apps/pre-processing-service/app/service/blog/blog_create_service.py
  apps/pre-processing-service/app/utils/s3_upload_util.py
Labels: enhancement
